version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/qna_dev
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - ALLOWED_HOSTS=localhost,127.0.0.1
    volumes:
      - .:/app
      - /app/__pycache__
    depends_on:
      - db
    command: >
      sh -c "scripts/wait-for-db.sh db 5432 &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=qna_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./scripts/init-dev.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data_dev: